version: "2"

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./php
    container_name: "laravel-php"
    volumes:
      - ./src:/src
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  mysql:
    image: mysql
    container_name: "laravel-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: shinya
    ports:
      - 3306:3306
    volumes:
      - dbdata2:/var/lib/mysql

  postgres:
    restart: always
    image: postgres:alpine
    container_name: "laravel-postgres"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: shinya
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    container_name: "laravel-redis"
    ports:
      - 6379:6379

volumes:
  dbdata2:
